import { Urbanist } from "next/font/google";
import "@/styles/globals.css";
import "@/styles/globalicons.css";

import { Slide } from "@/styles/slide";
import { Providers } from "@/config/providers";
import { MainNav } from "@/components/main-nav";
import { navigation } from "@/config/homepage"



const urbanist = Urbanist({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${urbanist.className} bg-[#201a17] text-white antialiased`}
      >
        <MainNav navigation={navigation} />
        <Providers>
            <Slide>{children}</Slide>
        </Providers>
      </body>
    </html>
  );
}
